### ISSUE TITLE
headers instead of header

### ISSUE THREAD

**Issue by Alvaro-Serquo** [KAL-ATM-Software/KAL_XFS4IoT_SP-Dev-Samples#1]
Running the program TestClient we have seen that the json sent to the endpoint has the field headers instead of header, as described in the xfs4iot documentation.

**Comment by seishinakano** [comment]
Thanks Alvaro.
You are right on this. the property name should be 'header' rather than 'headers'.
The reason of why KAL used 'headers' is because the XFS common interface had this property name 'headers' initially and corrected. However, KAL didn't update this fix internally in our SP framework accordingly.

We are tracking this issue internally and we will update SP framework once issue is addressed.

**Comment by seishinakano** [comment]
Hi Alvaro,
We are planning to add fix in the next package v0.0.2-alpha.2 including TextTerminal SP framework.
It will be published before next workshop planned on the 3rd August.

**Comment by seishinakano** [comment]
New package v0.0.2-alpha.2 addresses this issue.
